controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    if (RandomPick == 1) {
        info.changeScoreBy(1)
    }
    generate()
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (RandomPick == 0) {
        info.changeScoreBy(1)
    }
    generate()
})
function generate () {
    RandomPick = randint(0, 1)
    if (RandomPick == 0) {
        mySprite.sayText("push A")
    } else {
        mySprite.sayText("push B")
    }
}
let RandomPick = 0
let mySprite: Sprite = null
game.splash("Push A or B as Directed")
mySprite = sprites.create(img`
    ........................
    ........................
    ........................
    ........................
    .........fffff..........
    .......ffb1111ff........
    ......fb1111111bf.......
    ......f111111111f.......
    .....ffff1111111df......
    ....fb111c1dd111df......
    ....ffb1b1fdcf11bf......
    .....ffbfbfb11111f......
    ......ffffcfdb1b1f......
    .......fcccfcfbfbf......
    ........ffffffffff......
    .........ffffff.........
    .........ffffff.........
    .....f..fffffff.........
    .....fffffffff..........
    ......fffffff...........
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
info.startCountdown(20)
